### PR TITLE
Upgraded support for Mongoid 6

### PR DESCRIPTION
**Pull request by michaeltrimm**
Added support for Mongoid 6 and Rails 5. If you cannot wait for this pull request to be merged, you can be access and use it by pulling from https://github.com/michaeltrimm/doorkeeper-mongodb

### CODE REVIEW

**Comment by michaeltrimm** [comment]
Please fix access to codeclimate to allow contributors to see the output or remove the job from the pull request process.

**Comment by jasl** [comment]
Hi!
I remember that current Doorkeeper business logical use some ActiveRecord relates methods that make Doorkeeper-Mongoid failed to test (I've add some workaround before), do you test locally and pass all tests?

PS: I'm original Doorkeeper-Mongoid author but for personal reason I can't maintain the gem.

**Comment by michaeltrimm** [comment]
Hey, 

The branch that I have works for me, as for unit tests, the builds aren't working right now - they are failing for non-related PR reasons and I'm trying to debug it. When they start working again I'll be able to verify unit/functional test results. 

Right now, the build is trying to find the doorkeeper gem as referenced in the gemspec file and its reporting "Could not find gem 'doorkeeper (~> 3.0.0)' in". If we can get past that, we should be able to get Mongoid6 integrated. I've been using it in a staging environment for a while and it's been working fine for weeks - which is why I am working on this PR. 

Right now doorkeeper is on v4.2.0, so I am unsure why that request is failing, unless we modify the gemspec file to pull the ~> 3.0.0 from github and not rubygems?

Cheers, 
Michael

**Comment by michaeltrimm** [comment]
Please __fix__ the codeclimate permissions. The "Details" link reports 403 Forbidden for me and I am unable to address the problems.

**Comment by jasl** [comment]
ping @tute

**Comment by tute** [comment]
> Analysis results are provided for code written by licensed individuals, and Michael does not appear to be a member of your organization.

Looks like the report will be unavailable.

Also, ping @maclover7.

**Comment by zeitnot** [comment]
@michaeltrimm This patch seems good. But there is a problem related to doorkeeper gem. For instance, in Rails 5 you can not create an access token due to associations. To make it backward compatible the doorkeeper team hack it in [this](https://github.com/doorkeeper-gem/doorkeeper/blob/master/lib/doorkeeper/models/access_token_mixin.rb#L17)  section. But the fact is that there is not `ActiveRecord` class while using `Mongoid` gem.  I want to know that how you defeated it?

**Pull request closed without merging**
