### PR TITLE
Enable to reuse_access_toke

### PR DESCRIPTION
**Pull request by yokozawa0701**
resolve https://github.com/doorkeeper-gem/doorkeeper-mongodb/issues/86

### CODE REVIEW

**Review by nbulaj — COMMENTED** [review]
This will work only with newest doorkeeper version. We have either change version in the gem spec either add support for old im0lementations as well

**Comment by yokozawa0701** [comment]
@nbulaj 

Thanks for your review 😄 
I simply add keyword arguments, include_expired, with a default value. The new feature I added is only called when this argument is sent. So I think It is not a problem for doorkeepers with old versions, right?

**Comment by nbulaj** [comment]
> So I think It is not a problem for doorkeepers with old versions, right?

Yeah, I hope so.. Maybe internals are using `matching_token_for` but since kward has a default I hope it will be OK to use it with old gem versions as well. Thanks!

**Review by nbulaj — APPROVED** [review]

**Comment by yokozawa0701** [comment]
Thanks for merging!

**Pull request merged**
