### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by max-konin**
mongoid5 supports

### CODE REVIEW

**Comment by jasl** [comment]
Thank you!

**Comment by tute** [comment]
@jasl if you can, we could add it to https://github.com/doorkeeper-gem/doorkeeper-mongodb/blob/master/.travis.yml, and actually remove some old dependencies if we were to release different gem versions. Thank you all!

**Comment by jasl** [comment]
@tute No problem.
but [some logic of doorkeeper](https://github.com/doorkeeper-gem/doorkeeper/blob/master/lib/doorkeeper/oauth/authorization_code_request.rb#L24) rely on transaction which Mongoid doesn't support, I've did some patches to preventing raising error but some tests are still failing.
For better supporting Mongoid and other ORMs, we need to find a way to decouple those from ActiveRecord.

**Comment by tute** [comment]
How can we decouple a transaction from ActiveRecord and its databases? Do database engines that don't support them just ignore them?

**Comment by jasl** [comment]
For now, I [ignore them](https://github.com/doorkeeper-gem/doorkeeper-mongodb/blob/master/lib/doorkeeper-mongodb/compatible.rb), and MongoDB can't prove consistency, so no side effect here.
but as for a monkey patch, this really a tricky way, not a good taste.

I've considered before, and that may works (but for these months I working for a startup team, super lack of time).

My idea is, for example, you can treat [`Doorkeeper::OAuth::AuthorizationCodeRequest`](https://github.com/doorkeeper-gem/doorkeeper/blob/master/lib/doorkeeper/oauth/authorization_code_request.rb) as a service object, we can extract some 'atomic' business logic
```ruby
def before_successful_response
  grant.transaction do
    grant.lock!
    raise Errors::InvalidGrantReuse if grant.revoked?

    grant.revoke
    find_or_create_access_token(grant.application,
                                grant.resource_owner_id,
                                grant.scopes,
                                server)
  end
end
```
to
```ruby
def before_successful_response
  grant.generate_access_token!(server)
end
```
and moving it to `AccessGrant` model
```ruby
class Doorkeeper::AccessGrant
  def generate_access_token!(server)
    transaction do
      lock!
      raise Errors::InvalidGrantReuse if revoked?
      
      revoke
      find_or_create_access_token(application, resource_owner_id, scopes, server)
    end
  end
end
```
then, `AccessGrant#generate_access_token!(server)` becoming an interface that ORMs adapter could override it.

If we moving these 'atomic' logic to models and declare those clearly, and we don't use ORM specific methods directly (such as find, find_or_create, where, etc), an ORM adapter should know what does it must to implement, we can provide default implementations, but ORM adapters can override them if they need.

**Pull request merged**
